### ISSUE TITLE
__setitem__ to enable operations on coefficients

### ISSUE THREAD

**Issue by JulienNGirard** [neurospin/pisap#8]
Allow user to alter coefficients in a specific band/scale.
e.g.
```
wavelet=WaveletTransformBase.REGISTRY['HaarWaveletTransform'](nb_scale=5,verbose=1)
wavelet.data=<<myimageindirectspace>>
wavelet.analysis()
wavelet[2,2]*=0  # put band 2 of scale 2 to 0.
```

**Comment by AGrigis** [comment]
I have updated the code to handle slice properly.
Your use case still work. I have just added a test in pisap/test/test_analysis_synthesis -> test_accessors.
